### ISSUE TITLE
Can this work in linux as well, somehow?

### ISSUE THREAD

**Issue by michaelsjackson** [gbevin/MIDIRecorder#2]
Would be cool. Thanks for sharing the code / idea openly here. Merry Christmas!

**Comment by gbevin** [comment]
Not without a total rewrite, it's very much designed to benefit from Apple's infrastructure and APIs.

**Comment by michaelsjackson** [comment]
Ok, thanks for the clarification and the turbo fast reply.  Having something standalone in future would be cool. (Working in linux mainly). We need to work with sloppy timing until then.  :-)

**Comment by mxmilkiib** [comment]
A possible move to [iPlug2](https://github.com/iPlug2/iPlug2) would make that easier.
